### ISSUE TITLE
[BOJ] 공유기 설치

### ISSUE THREAD

**Issue by zsmalla** [RecoRecoNi/Algorithm-Study#266]
## Summary
<table>
  <tr>
    <th>Date</th>
    <td>2023-09-25</td>
  </tr>
  <tr>
    <th>Difficulty</th>
    <td>Gold 4</td>
  </tr>
  <tr>
    <th>Link</th>
    <td><a href='https://www.acmicpc.net/problem/2110' target='_blank' >https://www.acmicpc.net/problem/2110</a>
    </td>
  </tr>
</table>

## Insight

스터디를 진행하며 얻은 인사이트를 정리합니다.

**Comment by limstonestone** [comment]
도현이의 집이라니 풉킥

**Comment by zsmalla** [comment]
> 도현이의 집이라니 풉킥

누가 공유기를 200,000개나 설치해 도현시치
