### ISSUE TITLE
[BOJ] 제로

### ISSUE THREAD

**Issue by ksumini** [RecoRecoNi/Algorithm-Study#40]
## Summary
<table>
  <tr>
    <th>Date</th>
    <td>2023-06-01</td>
  </tr>
  <tr>
    <th>Difficulty</th>
    <td>Silver 4</td>
  </tr>
  <tr>
    <th>Link</th>
    <td><a href='https://www.acmicpc.net/problem/10773' target='_blank' >https://www.acmicpc.net/problem/10773</a>
    </td>
  </tr>
</table>

## Insight

스터디를 진행하며 얻은 인사이트를 정리합니다.

## BOJ
https://github.com/encrypted-def/basic-algo-lecture/blob/master/workbook/0x05.md

**Comment by zsmalla** [comment]
5명 코드리뷰(approved) 이후 머지 되었으므로 이슈 닫겠습니다!
